import type { AsyncSubscription, Options, SubscribeCallback } from '@parcel/watcher';
import { IGNORED_WORKSPACE_DIR_NAMES } from './workspace-file-scan';

/** Native matching avoids the expensive leading-** regex generated by Parcel's wrapper. */
export function workspaceWatcherOptions(platform = process.platform): Options & { ignoreGlobs: string[] } {
  const names = [...IGNORED_WORKSPACE_DIR_NAMES];
  const alternatives = names.map((name) => name.replace(/[\\^$.*+?()[\]{}|]/g, '\\$&')).join('|');
  const separator = platform === 'win32' ? '[\\\\/]' : '/';
  const component = platform === 'win32' ? '[^\\\\/]+' : '[^/]+';
  return {
    // Parcel's default probes Watchman through _popen on Windows, briefly
    // opening a console. Select the OS backend before that probe can run.
    backend: platform === 'win32' ? 'windows'
      : platform === 'darwin' ? 'fs-events'
        : platform === 'linux' ? 'inotify' : undefined,
    // Keep the named entry observable: it may be a regular file called
    // "build". Exclude descendants, pruning generated directory contents.
    ignoreGlobs: [`^(?:${component}${separator})*(?:${alternatives})${separator}.*$`],
  };
}

/** Close also owns a subscription that finishes starting after cancellation. */
export function startNativeWorkspaceWatcher(
  root: string,
  callback: SubscribeCallback,
  subscribe: (root: string, callback: SubscribeCallback, options: Options) => Promise<AsyncSubscription> = async (...args) => {
    // Missing native binaries must enter the manager's fallback, not crash imports.
    const watcher = await import('@parcel/watcher');
    return watcher.subscribe(...args);
  },
): { ready: Promise<void>; close(): Promise<void> } {
  let closed = false;
  let closePromise: Promise<void> | undefined;
  const pending = Promise.resolve().then(async () => {
    const options = workspaceWatcherOptions();
    return subscribe(root, (error, events) => {
      if (!closed) callback(error, events);
    }, options);
  });
  return {
    ready: pending.then(() => undefined),
    close() {
      closed = true;
      closePromise ??= pending.then((subscription) => subscription.unsubscribe(), () => undefined);
      return closePromise;
    },
  };
}
