async page => {
  const base = page.url().split('?')[0];
  const guard = async () => {
    if (!await page.locator('[data-automation-polish-fixture="synthetic"]').count()) throw new Error('Not the owned synthetic fixture');
  };
  const control = id => page.locator(`[data-ph-capture-attribute-control="${id}"]`);
  const open = async query => {
    await page.goto(base + query); await guard();
    await page.getByRole('button', { name: 'Open fixture manager', exact: true }).click();
    await page.locator('dialog[open]').waitFor();
  };
  const inspect = async () => {
    await control('automation.manager.close').click();
    await page.getByRole('button', { name: 'Inspect fixture writes' }).click();
    return JSON.parse(await page.getByLabel('Fixture writes').textContent());
  };
  const require = (condition, message) => { if (!condition) throw new Error(message); };
  await open('');
  await control('automation.autorun.start').waitFor();
  await control('automation.autorun.criteria').click();
  await page.locator('[name="constraints"]').fill('Preserve public API.\nKeep retained drafts.');
  await page.locator('[name="criteria"]').fill('Login regression passes.');
  await control('automation.autorun.criteria').click();
  await control('automation.form.save').click();
  const writes = await inspect();
  require(writes.length === 1, 'Exactly one explicit create expected');
  const input = writes[0].body;
  require(input.mode === 'autorun' && input.enabled === false, 'Save for later must stay disabled');
  require(input.trigger.delayMs === 120000 && input.limits.maxDispatches === 10 && input.autorun.maxAnalyses === 20, 'Collapsed default budgets changed');
  require(input.autorun.supervisor.model === 'gpt-6.1-sol' && input.autorun.supervisor.serviceTier === 'default', 'Supervisor changed');
  require(input.autorun.constraints.join('|') === 'Preserve public API.|Keep retained drafts.', 'Collapsed constraints lost');
  require(input.autorun.criteria[0].text === 'Login regression passes.', 'Collapsed criteria lost');
  // The browser must reveal/focus an invalid required field inside closed Advanced.
  await page.getByRole('button', { name: 'Open fixture manager', exact: true }).click();
  await control('automation.form.advanced').click();
  await page.locator('[name="name"]').fill('');
  await control('automation.form.advanced').click();
  await control('automation.form.save').click();
  require(await page.locator('[name="name"]').isVisible(), 'Invalid hidden Name field was not revealed');
  require(await page.locator('[name="name"]').evaluate(el => document.activeElement === el), 'Native validation did not focus Name');
  await page.locator('[name="name"]').fill('Retained corrected name');
  await control('automation.manager.close').click();
  require(await page.getByRole('button', { name: 'Open fixture manager', exact: true }).evaluate(el => document.activeElement === el), 'Close did not restore focus');
  await page.getByRole('button', { name: 'Open fixture manager', exact: true }).click();
  await control('automation.form.advanced').click();
  require(await page.locator('[name="name"]').inputValue() === 'Retained corrected name', 'Close discarded advanced draft');
  await control('automation.setup.heartbeat').click();
  await page.locator('[name="prompt"]').fill('Retained fixed instruction');
  await control('automation.setup.autorun').click();
  await control('automation.setup.heartbeat').click();
  require(await page.locator('[name="prompt"]').inputValue() === 'Retained fixed instruction', 'Method switch discarded Heartbeat draft');
  await page.getByRole('button', { name: 'Save for later', exact: true }).click();
  const heartbeat = (await inspect()).at(-1).body;
  require(heartbeat.enabled === false && heartbeat.prompt === 'Retained fixed instruction', 'Heartbeat save behavior changed');
  require(heartbeat.trigger.delayMs === 120000 && heartbeat.limits.maxDispatches === 10, 'Heartbeat defaults changed');
  await open('?idle');
  await control('automation.autorun.start').waitFor();
  require(await control('automation.autorun.start').isDisabled(), 'Consumed idle became startable');
  await control('automation.autorun.objective_edit').click();
  await page.locator('[name="objective"]').fill('Explicit goal cannot cure consumed idle');
  require(await control('automation.autorun.start').isDisabled(), 'Goal override manufactured readiness');
  require(await control('automation.history.open_session').first().isVisible(), 'Blocked state lost its next action');
  await open('?schedule');
  await page.locator('[name="prompt"]').fill('Review the changed files.');
  await page.locator('[name="at"]').fill('2027-01-16T09:00');
  await control('automation.form.save').first().click();
  const schedule = (await inspect())[0].body;
  require(schedule.enabled === true && schedule.trigger.kind === 'once' && schedule.limits.maxDispatches === 1, 'Explicit Schedule start/default changed');
  require(schedule.target.selection.model === 'fixture-model' && schedule.target.selection.reasoningEffort === 'high', 'Schedule launch selection changed');
  await open('?preview-error');
  await page.getByRole('alert').waitFor();
  require(await control('automation.setup.heartbeat').isVisible(), 'Failed preview hid the method choice');
  require(await control('automation.autorun.refresh').isVisible(), 'Failed preview hid explicit retry');
  await control('automation.setup.heartbeat').click();
  require(await page.locator('[name="prompt"]').isVisible(), 'Failed preview blocked Heartbeat');
  await page.keyboard.press('Escape');
  require(await page.locator('dialog[open]').count() === 0, 'Escape did not dismiss the top manager');
  require(await page.getByRole('button', { name: 'Open fixture manager', exact: true }).evaluate(el => document.activeElement === el), 'Escape lost invoker focus');
  return 'PASS: actual payloads, hidden validation focus, retained drafts, idle gating, Schedule defaults and Escape';
}
