async page => {
  const base = page.url().split('?')[0];
  if (!base.startsWith('http://172.17.241.221:34539/')) throw Error('Wrong owned fixture');
  const root = '/home/work/tmp/tessera-534-fast-setup-ui/screenshots';
  const control = id => page.locator(`[data-ph-capture-attribute-control="${id}"]`);
  const require = (value, message) => { if (!value) throw Error(message); };
  let index = 0;
  const shot = name => page.screenshot({path:`${root}/${String(++index).padStart(3,'0')}-${name}.png`});
  const load = async (query='',width=1440,height=1000) => {
    await page.setViewportSize({width,height}); await page.goto(base+'?'+query);
    require(await page.locator('[data-automation-polish-fixture="synthetic"]').count(),'Wrong page');
    await page.getByRole('button',{name:'Open fixture manager',exact:true}).click();
    await page.locator('dialog[open]').waitFor();
  };
  await load(); await page.waitForFunction(()=>!document.querySelector('[data-ph-capture-attribute-control="automation.autorun.start"]').disabled);
  await shot('autorun-default-wide');
  await control('automation.form.advanced').click(); await shot('autorun-expanded-wide');
  await page.locator('[name="constraints"]').fill('Preserve public API.\nKeep drafts.');
  await page.locator('[name="criteria"]').fill('Login regression passes.');
  await control('automation.form.advanced').click(); await control('automation.form.save').click();
  await control('automation.manager.close').click(); await page.getByRole('button',{name:'Inspect fixture writes'}).click();
  const saved = JSON.parse(await page.getByLabel('Fixture writes').textContent())[0].body;
  require(!saved.enabled && saved.autorun.constraints.length===2 && saved.autorun.criteria[0].text==='Login regression passes.','Closed fields lost');
  require(saved.trigger.delayMs===120000 && saved.limits.maxDispatches===10 && saved.autorun.maxAnalyses===20,'Defaults changed');
  await page.getByRole('button',{name:'Open fixture manager',exact:true}).click();
  await control('automation.form.advanced').click(); await page.locator('[name="name"]').fill('');
  await control('automation.form.advanced').click(); await control('automation.form.save').click();
  require(await page.locator('[name="name"]').isVisible(),'Hidden invalid field not revealed');
  require(await page.locator('[name="name"]').evaluate(el=>document.activeElement===el),'Invalid field not focused');
  await load('peek&language=ko',390,844); await page.locator('[name="supervisorModel"] option[value="gpt-6-astra"]').waitFor({state:'attached'});
  await shot('autorun-default-peek-390-ko'); await control('automation.form.advanced').click(); await shot('autorun-expanded-peek-390-ko');
  await page.locator('[data-automation-scroll]').evaluate(el=>el.scrollTop=el.scrollHeight); await shot('autorun-expanded-bottom-390-ko');
  require(await page.locator('dialog').evaluate(el=>el.scrollWidth<=el.clientWidth),'Dialog overflows');
  await load('loading',390,844); await page.locator('[aria-busy="true"]').first().waitFor();
  await page.locator('[name="objective"]').fill('Editable during slow checks');
  await page.locator('[name="supervisorModel"] option[value="gpt-6-astra"]').waitFor({state:'attached'});
  require(await control('automation.autorun.start').isDisabled(),'Pending check authorizes Start');
  require(await control('automation.autorun.refresh').count()===0,'Retry during check');
  await page.locator('[name="supervisorModel"]').selectOption('gpt-6-astra'); await page.locator('[name="supervisorEffort"]').selectOption('high');
  await shot('editable-pending-390');
  await control('automation.setup.heartbeat').click(); await page.locator('[name="prompt"]').fill('Fixed message');
  await control('automation.form.advanced').click(); await shot('heartbeat-expanded-390');
  await control('automation.setup.autorun').click(); require(await page.locator('[name="objective"]').inputValue()==='Editable during slow checks','Switch lost objective');
  await load('late'); await page.locator('[name="objective"]').fill('My edited goal must win');
  await page.waitForFunction(()=>!document.querySelector('[data-ph-capture-attribute-control="automation.autorun.start"]').disabled);
  require(await page.locator('[name="objective"]').inputValue()==='My edited goal must win','Late preview reset goal');
  await page.locator('[name="supervisorModel"]').selectOption('gpt-6-astra');
  require(await control('automation.autorun.start').isDisabled(),'Incomplete tuple authorizes Start');
  await page.locator('[name="supervisorEffort"]').selectOption('xhigh');
  await page.locator('[name="supervisorTier"]').selectOption('fast');
  await page.waitForFunction(()=>!document.querySelector('[data-ph-capture-attribute-control="automation.autorun.start"]').disabled);
  require(await page.locator('[name="objective"]').inputValue()==='My edited goal must win','Tuple change lost goal');
  await control('automation.autorun.start').click(); await control('automation.manager.close').click(); await page.getByRole('button',{name:'Inspect fixture writes'}).click();
  const selected=JSON.parse(await page.getByLabel('Fixture writes').textContent())[0].body.autorun.supervisor;
  require(selected.model==='gpt-6-astra'&&selected.reasoningEffort==='xhigh'&&selected.serviceTier==='fast','Selected tuple coerced');
  // Settings and Autorun use the same hook/cache/environment and displayed catalog.
  await page.locator('[data-settings-catalog] summary').click();
  const settingsModels=await page.locator('[data-settings-catalog] select').evaluateAll(els=>els.flatMap(el=>[...el.options].map(o=>[o.value,o.textContent])));
  await page.getByRole('button',{name:'Open fixture manager',exact:true}).click(); await page.getByRole('button',{name:'Claude Code',exact:true}).click();
  await page.locator('[name="supervisorModel"] option[value="opus"]').waitFor({state:'attached'});
  const models=await page.locator('[name="supervisorModel"] option').evaluateAll(els=>els.filter(el=>el.value).map(el=>[el.value,el.textContent]));
  require(models.every(model=>settingsModels.some(other=>JSON.stringify(other)===JSON.stringify(model))),'Settings catalog parity lost');
  await page.locator('[name="supervisorModel"]').selectOption('opus'); await page.locator('[name="supervisorEffort"]').selectOption('high');
  await page.getByText('This model could not be verified.',{exact:false}).waitFor();
  require(await page.locator('[name="supervisorModel"]').inputValue()==='opus','Unsupported alias replaced');
  require(await control('automation.autorun.start').isDisabled(),'Alias authorized'); await shot('claude-alias-recovery-wide');
  await load('idle',390,844); await page.getByText('Send a new worker instruction before Autorun can start.').waitFor();
  require(await page.getByRole('button',{name:'Add objective to Session draft'}).isVisible(),'New Start recovery missing'); await shot('new-start-recovery-390');
  await load('resume-error',390,844); await page.getByRole('button',{name:'Resume',exact:true}).waitFor();
  await page.waitForFunction(()=>!document.querySelector('[data-ph-capture-attribute-control="automation.manager.enable"]').disabled);
  await page.getByRole('button',{name:'Resume',exact:true}).click(); await page.locator('[aria-busy="true"]').waitFor();
  require(await page.getByRole('alert').count()===0,'Stale error alongside spinner'); await shot('rejected-resume-refresh-390');
  await page.getByText('Send a new worker instruction before resuming.').waitFor();
  require(await page.getByRole('button',{name:'Resume',exact:true}).isDisabled(),'Rejected ready state restored');
  require(await page.getByRole('button',{name:'Edit',exact:true}).count()===1,'Duplicate Edit actions'); await shot('saved-resume-recovery-390');
  return `PASS ${index} screenshots: editable/draft/catalog/exact-payload/hidden-validation/rejection/recovery (synthetic only)`;
}
