import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import type { CliProvider } from '@/lib/cli/providers/types';

const root = fs.mkdtempSync(path.join(os.tmpdir(), 'tessera-git-source-ai-'));
process.env.TESSERA_DATA_DIR = path.join(root, 'data');
process.env.TESSERA_PRODUCTION_DB = '1';

const repo = path.join(root, 'repo');
fs.mkdirSync(repo, { recursive: true });
execFileSync('git', ['init', '-b', 'main'], { cwd: repo, stdio: 'ignore' });
execFileSync('git', ['config', 'user.email', 'test@example.com'], { cwd: repo });
execFileSync('git', ['config', 'user.name', 'Tessera Test'], { cwd: repo });
fs.writeFileSync(path.join(repo, 'selected.txt'), 'selected content\n');

test('Source Control AI settings select the one-shot provider and model', async () => {
  const [{ cliProviderRegistry }, { SettingsManager }, service] = await Promise.all([
    import('../src/lib/cli/providers/registry'),
    import('../src/lib/settings/manager'),
    import('../src/lib/git/git-commit-message-service'),
  ]);
  const calls: Array<{ prompt: string; userId?: string; model?: string }> = [];
  cliProviderRegistry.register('test-source-control', {
    generateText: async (prompt: string, userId?: string, model?: string) => {
      calls.push({ prompt, userId, model });
      return { text: 'feat: generated from worktree' };
    },
  } as unknown as CliProvider);

  const userId = 'source-control-ai-user';
  const settings = await SettingsManager.load(userId);
  await SettingsManager.save(userId, {
    ...settings,
    gitConfig: {
      ...settings.gitConfig,
      sourceControlAi: {
        provider: 'test-source-control',
        model: 'model-for-git',
      },
    },
  });

  const message = await service.generateConfiguredCommitMessage(
    { workDir: repo, agentEnvironment: 'wsl' },
    userId,
    ['selected.txt'],
  );

  assert.equal(message, 'feat: generated from worktree');
  assert.equal(calls.length, 1);
  assert.equal(calls[0]?.userId, userId);
  assert.equal(calls[0]?.model, 'model-for-git');
  assert.match(calls[0]?.prompt ?? '', /selected\.txt/);
  assert.match(calls[0]?.prompt ?? '', /selected content/);
});

test('a Session provider remains a fallback when the configured default is unavailable', async () => {
  const [{ cliProviderRegistry }, { SettingsManager }, service] = await Promise.all([
    import('../src/lib/cli/providers/registry'),
    import('../src/lib/settings/manager'),
    import('../src/lib/git/git-commit-message-service'),
  ]);
  cliProviderRegistry.register('unavailable-source-control', {
    generateText: async () => null,
  } as unknown as CliProvider);
  cliProviderRegistry.register('session-fallback', {
    generateText: async () => ({ text: 'fix: generated by session fallback' }),
  } as unknown as CliProvider);

  const userId = 'source-control-ai-fallback-user';
  const settings = await SettingsManager.load(userId);
  await SettingsManager.save(userId, {
    ...settings,
    gitConfig: {
      ...settings.gitConfig,
      sourceControlAi: { provider: 'unavailable-source-control', model: '' },
    },
  });

  const message = await service.generateConfiguredCommitMessage(
    { workDir: repo, agentEnvironment: 'wsl' },
    userId,
    ['selected.txt'],
    'session-fallback',
  );
  assert.equal(message, 'fix: generated by session fallback');
});
