export const TELEMETRY_UI_SURFACES = [
  'workspace_header',
  'workspace_board',
  'workspace_list',
  'tab_bar',
  'new_session',
  'collection_create',
  'composer',
  'chat_header',
  'task_menu',
  'right_panel',
  'git_panel',
  'files_panel',
  'memory_panel',
  'scripts_panel',
  'folder_browser',
  'settings',
  'setup',
  'auth',
  'sidebar',
  'archive',
  'message',
  'message_search',
  'agent_prompt',
  'terminal',
  'workspace_editor',
  'notifications',
  'skills',
  'feedback',
  'running_processes',
  'app_window',
  'worktree',
  'dialog',
] as const;

export type TelemetryUiSurface = (typeof TELEMETRY_UI_SURFACES)[number];

export const TELEMETRY_UI_CONTROLS = [
  'workspace.view.list',
  'workspace.view.kanban',
  'board.chat.open',
  'board.task.open',
  'board.subsession.open',
  'board.collection_filter.all',
  'board.collection_filter.select',
  'board.project_filter.all',
  'board.project_filter.select',
  'board.running_filter.all',
  'board.running_filter.running',
  'board.popout',
  'list.chat.open',
  'list.task.open',
  'list.subsession.open',
  'list.task.add_session',
  'collection.menu.open',
  'collection.edit',
  'collection.delete',
  'sidebar.toggle',
  'tab.new',
  'tab.select',
  'tab.close',
  'tab.list.open',
  'tab.list.select',
  'tab.list.close',
  'right_panel.toggle',
  'right_panel.close',
  'right_panel.tab.git',
  'right_panel.tab.files',
  'right_panel.tab.scripts',
  'right_panel.tab.memory',
  'right_panel.tab.images',
  'creation.mode.chat',
  'creation.mode.task',
  'creation.mode.shell',
  'creation.submit',
  'creation.submit.chat',
  'creation.submit.task',
  'creation.cancel',
  'creation.collection.select',
  'creation.provider.select',
  'creation.provider.refresh',
  'creation.provider.feedback',
  'composer.quick_create',
  'composer.attach',
  'composer.voice',
  'composer.stop',
  'composer.send',
  'composer.send_while_running',
  'chat_header.terminal_toggle',
  'chat_header.search',
  'chat_header.more',
  'chat_header.close_panel',
  'panel.split.open',
  'panel.split.right',
  'panel.split.down',
  'panel.close',
  'task.stop',
  'task.restart',
  'task.menu.open',
  'task.status.change',
  'task.generate_title',
  'task.run_preparation',
  'task.archive_toggle',
  'task.rename',
  'task.open_new_tab',
  'task.delete',
  'git.action_menu.open',
  'git.action.commit',
  'git.action.commit_push',
  'git.action.push',
  'git.action.pull',
  'git.action.create_pr',
  'git.action.open_source_control',
  'git.action.abort',
  'git.primary.commit',
  'git.primary.conflict',
  'git.primary.push',
  'git.primary.publish',
  'git.primary.pull',
  'git.primary.create_pr',
  'git.primary.view_pr',
  'git.primary.archive_worktree',
  'git.primary.loading',
  'git.primary.up_to_date',
  'git.generate_commit_message',
  'git.repository.open',
  'git.pull_request.open',
  'git.worktree_folder.open',
  'git.worktree_path.copy',
  'git.branch.copy',
  'git.commit_file.toggle',
  'git.commit_file.toggle_all',
  'git.file.diff_open',
  'git.file.open',
  'git.file.copy_path',
  'git.default_branch_confirm.accept',
  'git.default_branch_confirm.cancel',
  'git.revert_selected.open',
  'git.revert.confirm.accept',
  'git.revert.confirm.cancel',
  'files.directory.toggle',
  'files.file.open',
  'files.new_file',
  'files.new_folder',
  'files.hidden.toggle',
  'memory.file.open',
  'memory.file.delete',
  'memory.retry',
  'memory.create.open',
  'memory.create.confirm',
  'memory.create.cancel',
  'memory.delete.confirm',
  'memory.delete.cancel',
  'scripts.settings.open',
  'scripts.preparation.run',
  'scripts.phase.toggle',
  'folder_browser.environment.wsl',
  'folder_browser.environment.native',
  'folder_browser.path.go',
  'folder_browser.root',
  'folder_browser.breadcrumb',
  'folder_browser.hidden.toggle',
  'folder_browser.retry',
  'folder_browser.parent',
  'folder_browser.entry',
  'folder_browser.cancel',
  'folder_browser.feedback',
  'folder_browser.confirm',
  'settings.open',
  'settings.close',
  'settings.overlay_close',
  'settings.feedback.open',
  'settings.section_picker.open',
  'settings.section.general',
  'settings.section.project',
  'settings.section.appearance',
  'settings.section.models',
  'settings.section.remote_access',
  'settings.section.development',
  'settings.section.git',
  'settings.general.language',
  'settings.general.execution_mode',
  'settings.general.default_cli_provider',
  'settings.general.new_session_kind',
  'settings.general.terminal_view',
  'settings.profile.display_name',
  'settings.profile.avatar_preset',
  'settings.profile.avatar_upload',
  'settings.profile.avatar_reset',
  'settings.notifications.sound',
  'settings.notifications.toast',
  'settings.notifications.ai_title_generation',
  'settings.translate.expand',
  'settings.translate.enabled',
  'settings.translate.source_language',
  'settings.translate.target_language',
  'settings.translate.shortcut',
  'settings.translate.input_provider',
  'settings.translate.input_model',
  'settings.translate.input_prompt',
  'settings.translate.input_prompt_reset',
  'settings.translate.output_provider',
  'settings.translate.output_model',
  'settings.translate.output_prompt',
  'settings.translate.output_prompt_reset',
  'settings.updates.check',
  'settings.updates.copy_command',
  'settings.updates.open_release',
  'settings.updates.show_again',
  'settings.updates.dismiss',
  'settings.telemetry.enabled',
  'settings.window.close_behavior',
  'settings.keyboard.enter_behavior',
  'settings.keyboard.shortcut_edit',
  'settings.keyboard.shortcut_reset',
  'settings.keyboard.shortcut_reset_all',
  'settings.keyboard.conflict_cancel',
  'settings.keyboard.conflict_confirm',
  'settings.appearance.theme',
  'settings.appearance.kanban_open_mode',
  'settings.appearance.terminal_theme',
  'settings.appearance.font_size',
  'settings.appearance.inactive_panel_dimming',
  'settings.appearance.provider_icons',
  'settings.appearance.recent_work',
  'settings.project.selector',
  'settings.project.before_script',
  'settings.project.after_script',
  'settings.project.ignored_files_expand',
  'settings.project.ignored_file_toggle',
  'settings.models.custom_input',
  'settings.models.custom_add',
  'settings.models.custom_remove',
  'settings.remote.firewall_configure',
  'settings.remote.address_candidate',
  'settings.remote.address_input',
  'settings.remote.address_save',
  'settings.remote.pairing_issue',
  'settings.remote.pairing_copy_link',
  'settings.remote.pairing_rotate',
  'settings.remote.pairing_deny',
  'settings.remote.pairing_approve',
  'settings.remote.devices_refresh',
  'settings.remote.devices_retry',
  'settings.remote.device_disconnect',
  'settings.remote.devices_disconnect_all',
  'settings.remote.revocation_cancel',
  'settings.remote.revocation_confirm',
  'settings.development.agent_environment',
  'settings.development.tessera_cli_enabled',
  'settings.development.cli_command_override',
  'settings.development.cli_command_clear',
  'settings.development.cli_status_refresh',
  'settings.development.tool_status_refresh',
  'settings.development.diagnostics_run',
  'settings.development.diagnostics_export',
  'settings.development.worktree_auto_delete',
  'settings.development.worktree_retention_days',
  'settings.development.worktree_retention_cancel',
  'settings.development.worktree_retention_confirm',
  'settings.development.worktree_path_template',
  'settings.git.branch_prefix',
  'settings.git.ai_provider',
  'settings.git.ai_model',
  'setup.advanced.toggle',
  'setup.continue',
  'setup.status.refresh',
  'setup.environment.native',
  'setup.environment.wsl',
  'setup.execution_mode',
  'setup.tessera_cli_enabled',
  'setup.account.username',
  'setup.account.password',
  'setup.account.create',
  'auth.username',
  'auth.password',
  'auth.login',
  'sidebar.project.add',
  'sidebar.project.select',
  'sidebar.all_projects.open',
  'sidebar.archive.open',
  'sidebar.feedback.open',
  'sidebar.skills.open',
  'sidebar.github_star',
  'sidebar.project.remove',
  'sidebar.filter.all',
  'sidebar.filter.running',
  'sidebar.running.stop_all',
  'sidebar.groups.toggle_all',
  'sidebar.section.toggle',
  'sidebar.collection.create_input',
  'sidebar.collection.create_open',
  'composer.provider.select',
  'composer.model.open',
  'composer.model.select',
  'composer.effort.open',
  'composer.effort.select',
  'composer.access.open',
  'composer.access.select',
  'composer.fast.toggle',
  'composer.plan.toggle',
  'agent_prompt.density.decrease',
  'agent_prompt.density.increase',
  'agent_prompt.option.select',
  'agent_prompt.other_input',
  'agent_prompt.retry',
  'agent_prompt.submit',
  'agent_prompt.permission.allow',
  'agent_prompt.permission.deny',
  'agent_prompt.permission.expand',
  'agent_prompt.plan.allow',
  'agent_prompt.plan.deny',
  'agent_prompt.plan.expand',
  'archive.retry',
  'archive.search',
  'archive.project_filter',
  'archive.auto_delete',
  'archive.retention_days',
  'archive.bulk_delete',
  'archive.load_more',
  'archive.item.restore',
  'archive.item.delete',
  'archive.item.delete_worktree',
  'archive.session.open',
  'archive.dialog.cancel',
  'archive.dialog.confirm',
  'message.translate',
  'message.copy',
  'message.fork',
  'message.image.open',
  'message.image.zoom_out',
  'message.image.zoom_in',
  'message.image.zoom_reset',
  'image_generation.retry',
  'image_generation.input.open',
  'image_generation.input.download',
  'image_generation.result.open',
  'image_generation.result.download',
  'image_generation.prompt.copy',
  'image_generation.prompt.toggle',
  'image_generation.codex_prompt.toggle',
  'message.tool.toggle',
  'message.thinking.toggle',
  'message.code.copy',
  'message.result.open',
  'message.voice.cancel',
  'message.load_more',
  'message.scroll_bottom',
  'list.selection.done',
  'list.selection.stop',
  'list.selection.open_split_view',
  'list.selection.archive',
  'list.selection.delete',
  'list.selection.clear',
  'message_search.input',
  'message_search.previous',
  'message_search.next',
  'message_search.close',
  'terminal.special_key',
  'terminal.attach',
  'terminal.input',
  'terminal.send',
  'terminal.action',
  'terminal.scroll_bottom',
  'terminal.restart',
  'workspace_editor.preview',
  'workspace_editor.source',
  'workspace_editor.close',
  'workspace_editor.retry',
  'workspace_editor.save',
  'workspace_editor.open_host',
  'workspace_editor.copy_content',
  'workspace_editor.copy_path',
  'workspace_editor.reload',
  'workspace_editor.overwrite',
  'workspace_editor.cancel',
  'workspace_editor.image_retry',
  'workspace_editor.image_zoom_out',
  'workspace_editor.image_zoom_reset',
  'workspace_editor.image_zoom_in',
  'workspace_editor.context.new_file',
  'workspace_editor.context.new_folder',
  'workspace_editor.context.open',
  'workspace_editor.context.reveal',
  'workspace_editor.context.copy_path',
  'workspace_editor.context.rename',
  'workspace_editor.context.delete',
  'workspace_editor.delete.cancel',
  'workspace_editor.delete.confirm',
  'notifications.open',
  'notifications.mark_all_read',
  'notifications.dismiss_all',
  'notifications.item.open',
  'notifications.toast.action',
  'notifications.toast.dismiss',
  'skills.item.toggle',
  'skills.favorite.toggle',
  'skills.model.open',
  'skills.model.select',
  'skills.analysis.cancel',
  'skills.analysis.refresh',
  'skills.tab.select',
  'skills.search',
  'feedback.close',
  'feedback.message',
  'feedback.email',
  'feedback.cancel',
  'feedback.submit',
  'git.failure.dismiss',
  'git.failure.expand',
  'git.failure.copy',
  'git.commit.open',
  'git.commit.close',
  'git.commit.include_toggle',
  'git.changed_files.toggle',
  'git.conflict.ai_prepare',
  'git.diff.copy',
  'git.diff.previous',
  'git.diff.next',
  'git.section.toggle',
  'memory.preview',
  'memory.edit',
  'memory.save',
  'memory.copy',
  'memory.close',
  'memory.reload',
  'memory.overwrite',
  'tab.scroll.previous',
  'tab.scroll.next',
  'tab.context.close',
  'tab.context.close_others',
  'tab.context.close_left',
  'tab.context.close_right',
  'tab.context.close_all',
  'tab.rename',
  'board.column.add_chat',
  'board.scroll.previous',
  'board.scroll.next',
  'board.peek.close',
  'board.peek.terminal_mode',
  'board.task.add_session',
  'board.task.sessions.toggle',
  'chat.retry',
  'chat.panel.release',
  'collection.rename_input',
  'collection.quick_create.open',
  'collection.move.open',
  'collection.move.select',
  'collection.subsessions.toggle',
  'creation.sheet.close',
  'creation.collection.input',
  'creation.task.title_input',
  'creation.task.branch_input',
  'composer.input',
  'composer.attachment.remove',
  'composer.voice.stop',
  'composer.skill.remove',
  'composer.skill_favorites.open',
  'composer.skill_favorites.run',
  'composer.skill_favorites.remove',
  'composer.skill_favorites.add_open',
  'composer.skill_favorites.search',
  'composer.skill_favorites.add',
  'composer.skill.select',
  'composer.reference.select',
  'composer.reference.retry',
  'composer.reference.remove',
  'composer.provider.refresh',
  'folder_browser.path_input',
  'chat_header.title_input',
  'chat_header.title_save',
  'chat_header.title_cancel',
  'chat_header.title_action',
  'message.image.close',
  'message.error.toggle',
  'message.mcp_error.toggle',
  'message.tool_detail.close',
  'message.workflow.toggle',
  'message.workflow.dismiss',
  'terminal.chat.cancel',
  'terminal.chat.input',
  'terminal.chat.send',
  'terminal.chat.open_terminal',
  'git.commit.message',
  'memory.create.name',
  'task.rename_input',
  'creation.project.add',
  'creation.project.select',
  'creation.execution_mode',
  'creation.worktree.source',
  'creation.worktree.base_ref',
  'creation.error.dismiss',
  'git.diff.close',
  'files.search',
  'files.inline_input',
  'collection.section.toggle',
  'message.link.open',
  'message.pr.open',
  'message.todo.toggle',
  'dialog.close',
  'sidebar.provider_usage.open',
  'board.popout.close',
  'running_processes.toggle',
  'running_processes.stop_all',
  'running_processes.navigate',
  'running_processes.stop',
  'app_window.minimize',
  'app_window.maximize',
  'app_window.close',
  'app_window.close_dialog.cancel',
  'app_window.close_dialog.remember',
  'app_window.close_dialog.quit',
  'app_window.close_dialog.tray',
  'app_window.menu.open',
  'worktree.select',
  'worktree.warning.dismiss',
  'worktree.peek.close',
  'task.preparation.open',
  'pairing.retry',
] as const;

export type TelemetryUiControl = (typeof TELEMETRY_UI_CONTROLS)[number];
export type SettingsTelemetryControl = Extract<TelemetryUiControl, `settings.${string}`>;

export const SETTINGS_SECTION_TELEMETRY_CONTROLS = {
  general: 'settings.section.general',
  project: 'settings.section.project',
  appearance: 'settings.section.appearance',
  models: 'settings.section.models',
  'remote-access': 'settings.section.remote_access',
  development: 'settings.section.development',
  git: 'settings.section.git',
} as const satisfies Record<string, SettingsTelemetryControl>;

export interface TelemetryClickAttributes {
  'data-ph-capture': 'true';
  'data-ph-capture-attribute-control': TelemetryUiControl;
  'data-ph-capture-attribute-surface': TelemetryUiSurface;
}

export interface TelemetryTarget {
  control: TelemetryUiControl;
  surface: TelemetryUiSurface;
}

export const TELEMETRY_IGNORE_REASONS = [
  'drag_only',
  'event_boundary',
  'hidden_file_input',
  'wrapper_instrumented',
  'non_action',
  'manual_capture',
] as const;

export type TelemetryIgnoreReason = (typeof TELEMETRY_IGNORE_REASONS)[number];

export interface TelemetryIgnoreAttributes {
  'data-telemetry-ignore': TelemetryIgnoreReason;
}

const allowedUiControls = new Set<string>(TELEMETRY_UI_CONTROLS);
const allowedUiSurfaces = new Set<string>(TELEMETRY_UI_SURFACES);

export function telemetryClickAttributes(
  control: TelemetryUiControl,
  surface: TelemetryUiSurface,
): TelemetryClickAttributes {
  return {
    'data-ph-capture': 'true',
    'data-ph-capture-attribute-control': control,
    'data-ph-capture-attribute-surface': surface,
  };
}

export function settingsTelemetryClickAttributes(
  control: SettingsTelemetryControl,
): TelemetryClickAttributes {
  return telemetryClickAttributes(control, 'settings');
}

export function telemetryTargetAttributes(
  target?: TelemetryTarget,
): TelemetryClickAttributes | Record<string, never> {
  return target
    ? telemetryClickAttributes(target.control, target.surface)
    : {};
}

export function telemetryIgnoreAttributes(
  reason: TelemetryIgnoreReason,
): TelemetryIgnoreAttributes {
  return { 'data-telemetry-ignore': reason };
}

export function isTelemetryUiControl(value: unknown): value is TelemetryUiControl {
  return typeof value === 'string' && allowedUiControls.has(value);
}

export function isTelemetryUiSurface(value: unknown): value is TelemetryUiSurface {
  return typeof value === 'string' && allowedUiSurfaces.has(value);
}

export function sanitizeAutocaptureClickProperties(
  properties: Record<string, unknown>,
): { control: TelemetryUiControl; surface: TelemetryUiSurface } | null {
  const control = properties.control;
  const surface = properties.surface;

  if (
    !isTelemetryUiControl(control)
    || !isTelemetryUiSurface(surface)
  ) {
    return null;
  }

  return {
    control,
    surface,
  };
}
